
spring:
  application:
    name: draw-service
  datasource:
    url: jdbc:mysql://localhost:3306/draw?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1q2w3e4r!!
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

